# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 7f9186a01efa2dafd2b3cb2cb3a656f33d059c7e197a435ca20205151b9bdcd2a4d2110f86331cc890534af25766fcbb9f3b76d631813c809038000034b734b9

test:
  secret_key_base: 4a8a2635a3781138db914aa8589ffd6affc618e2d80122342654bc3cb5b8344194e6397842eb3f5dca92bf600d494e3083cbf6881186d28612e76cc3d8237513

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
